Completed homework 5
diduk001/tinkoff-java-course pull request #11
Opened 2023-11-10 18:45 UTC by diduk001

2023-12-06 12:38 UTC, VictorMinsky requested changes

2023-12-06 12:38 UTC, VictorMinsky commented on src/main/java/edu/hw5/DateParser/DaysAgoParser.java
> +        String[] words = string.split(" ");
`\\s+`

2023-12-06 12:38 UTC, VictorMinsky commented on src/main/java/edu/hw5/DateParser/DateParser.java
> +    }
Хотелось бы иметь возможность снаружи передавать список парсеров в конструктор твоего класса. Тогда можно было бы не заморачиваться с priority и считать, что парсеры надо вызывать в порядке переданном пользователем

2023-12-06 12:38 UTC, VictorMinsky commented on src/main/java/edu/hw5/SubstringChecker.java
> +        Pattern patternMatcher = Pattern.compile("^.*" + Pattern.quote(s) + ".*$");
Задача не про подстроки (substring), а подпоследовательности (subsequence)

2023-12-06 12:38 UTC, VictorMinsky commented on src/main/java/edu/hw5/NextFriday13thFinder.java
> +        final int THIRTEEN = 13;
В поле класса

2023-12-06 12:38 UTC, VictorMinsky commented on src/main/java/edu/hw5/OneZeroRegex.java
> +    // Task 7
Стоило всё-таки придерживаться идее, что задание == пакет (папка). А то у тебя всё в одной куче лежит, так ещё где-то в одном файле два задания, а где-то одно задание в двух файлах)

2023-12-08 08:44 UTC, diduk001 commented on src/main/java/edu/hw5/NextFriday13thFinder.java
> +        final int THIRTEEN = 13;
Сделал, ага. А в каком случае лучше помещать в поле класса, а в каком - в функцию?

2023-12-08 08:44 UTC, diduk001 commented on src/main/java/edu/hw5/SubstringChecker.java
> +        Pattern patternMatcher = Pattern.compile("^.*" + Pattern.quote(s) + ".*$");
Понял, исправлю. Просто раньше, кажется, было именно про подстроки

2023-12-08 08:46 UTC, diduk001 commented on src/main/java/edu/hw5/DateParser/DaysAgoParser.java
> +        String[] words = string.split(" ");
Понял, ага

2023-12-08 10:09 UTC, VictorMinsky commented on src/main/java/edu/hw5/SubstringChecker.java
> +        Pattern patternMatcher = Pattern.compile("^.*" + Pattern.quote(s) + ".*$");
А где исправления, в коммите не вижу?

2023-12-08 18:09 UTC, diduk001 commented on src/main/java/edu/hw5/SubstringChecker.java
> +        Pattern patternMatcher = Pattern.compile("^.*" + Pattern.quote(s) + ".*$");
Ой, чёт проглядел. Исправлю

2023-12-09 10:31 UTC, VictorMinsky approved these changes
OK

2023-12-10 19:20 UTC, merged