Completed homework 3
diduk001/tinkoff-java-course pull request #7
Opened 2023-10-22 13:59 UTC by diduk001

2023-11-06 21:22 UTC, VictorMinsky requested changes
Добавь меня, пожалуйста, в контрибьюторы репозитория, чтобы я мог резолвить треды с замечаниями.

Гайд -- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task1.java
Каждое задание надо было делать в отдельном пакете (папке)

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task1.java
> +            'W', 'X', 'Y', 'Z'};
Как вариант, но высок шанс опечаться и пропустить символ. Кажется, что лучше сделать цикл от `'a' ... 'z'` и `'A' ... 'Z'`

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task2.java
> +        ArrayList<String> result = new ArrayList<>();
Слева обычно указывается интерфейс (здесь `List`), а справа реализация (здесь `ArrayList`)

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task3.java
> +            result.put(object, oldValue + 1);
Сделай через `getOrDefault`

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task5.java
> +    }
Вынеси в отдельный файл

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task6.java
> +    }
Вынеси в отдельный файл

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task6.java
> +    }
Вынеси в отдельный файл

2023-11-06 21:22 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task7.java
> +            }
А если ни o1, ни o2 не null? Тогда их надо сравнивать как обычные объекты

2023-11-07 08:31 UTC, diduk001 commented on src/main/java/edu/hw3/Task1.java
Отправил инвайт

2023-11-07 11:07 UTC, diduk001 commented on src/main/java/edu/hw3/Task7.java
> +            }
Понял, что ты имеешь в виду, но не очень понимаю, как реализовать этот случай и как сравнивать да объекта, о которых мы ничего не знаем. Можно ли поставить `Comparator<Integer>`?

2023-11-07 17:32 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task1.java
Пришло, спасибо

2023-11-07 17:35 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task7.java
> +            }
Не заметил этот момент. Тебе надо было использовать дженерики, у тебя тогда класс выглядит бы как `public class NullComparator<T extends Comparable<T>> implements Comparator<T> ` и в таком случае ты бы смог сделать при равенстве `o1.compareTo(o2)`

2023-11-07 17:38 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task7.java
> +            }
Ещё я не заметил, что ты делаешь `o1 == o2`, это неправильно, `==` сравнивает по ссылке, а не значению.
Вот такой код выдаёт неожиданный результат для `==`:
```java
String a = "123";
String b = new String("123");
System.out.println(a == b); // false
System.out.println(a.equals(b)); // true
```

2023-11-07 17:45 UTC, VictorMinsky requested changes
Молодец, 7ую таску пофиксь и будет ОК.
Ещё по мелочи:
1) Стоит оставлять какой-то комментарий в каждом ишью, даже если это просто `fixed`, `согл` или что-то более подробное
2) Ишью обычно резолвит тот, кто их оставил, чтобы убедиться, что всё правильно было исправлено. Тебе не стоит это делать

2023-11-07 17:45 UTC, VictorMinsky commented on src/main/java/edu/hw3/Task3/WordCounter.java
> +            Integer oldValue = result.getOrDefault(object, 0);
Почти, стоит заинлайнить `oldValue`, нет смысла выносить в переменную

2023-11-08 17:17 UTC, diduk001 commented on src/main/java/edu/hw3/Task3/WordCounter.java
> +            Integer oldValue = result.getOrDefault(object, 0);
Хорошо, понял, спасибо большое! Сейчас исправлю, запушу

2023-11-08 17:24 UTC, diduk001 commented on src/main/java/edu/hw3/Task7.java
> +            }
Понял, спасибо! Пытался на дженериках сделать, но не придумал, как сделать, забыл про `extends`. Про `==` тоже знал, но совсем не заметил почему-то

2023-11-12 16:51 UTC, VictorMinsky approved these changes
OK

Молодец!

2023-11-12 18:45 UTC, merged