Completed homework 4
diduk001/tinkoff-java-course pull request #8
Opened 2023-11-04 00:57 UTC by diduk001

2023-11-12 21:29 UTC, VictorMinsky requested changes

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        animals.sort(Comparator.comparingInt(Animal::height));
inline

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        return animals.subList(0, Math.min(k, animals.size()));
Перепиши на стримы. В помощь `limit`

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        return typeCounter;
Перепиши на стримы. В помощь `Collectors.groupingBy`, `Collectors.collectingAndThen`

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +    public static List<Animal> sortAnimalByHeight(List<Animal> animals) {
К каждой функции было бы неплохо написать комментарием номер задания и его условие

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        return Collections.max(
Перепиши на стримы. В помощь `.max`

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        }
Перепиши на стримы. В помощь `.count`

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        }
Перепиши на стримы. В помощь `.collect`, `.toMap`

2023-11-12 21:29 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        return animals.get(k - 1);
Перепиши на стримы. В помощь `.skip`, `.findFirst`

2023-11-13 10:36 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        animals.sort(Comparator.comparingInt(Animal::height));
переделал

2023-11-13 10:36 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        return animals.subList(0, Math.min(k, animals.size()));
ага, сделал

2023-11-13 10:52 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        return typeCounter;
Нашёл ещё такую штуку - `Collectors.counting()`, но она возвращает `Long`. Переписал на неё, потому что выглядит как примерно то, что надо, но пока не придумал, как переписать на возврат `Integer`

2023-11-13 11:39 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        return typeCounter;
Каст просто сделай и всё

2023-11-14 09:02 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        return animals.get(k - 1);
сделано

2023-11-14 09:02 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        }
сделал

2023-11-14 09:02 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        }
сделал, ага

2023-11-14 09:03 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        return Collections.max(
сделал

2023-11-14 09:03 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +    public static List<Animal> sortAnimalByHeight(List<Animal> animals) {
подписал, ага

2023-11-14 09:04 UTC, diduk001 commented on src/main/java/edu/hw4/Main.java
> +        return typeCounter;
как я понял, там не кастуется просто так, потому что колектор. сделал [вот так](https://stackoverflow.com/a/65125248/13283436), через `collectingAndThen`

2023-11-15 07:54 UTC, VictorMinsky commented on src/main/java/edu/hw4/Main.java
> +        return typeCounter;
Да, как вариант

2023-11-15 07:56 UTC, VictorMinsky approved these changes
OK

Молодец

2023-11-15 08:46 UTC, merged